cargo-features = ["codegen-backend"]


[package]
name = "bevy-template-0_14"
version = "0.1.0"
edition = "2021"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1
codegen-backend = "cranelift"

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
codegen-backend = "llvm"

[dependencies]
bevy = { version = "0.14.2", features = ["dynamic_linking"] }

[unstable]
codegen-backend = true


